### ISSUE TITLE
Missing Floating UI Size Middleware

### ISSUE THREAD

**Issue by aaronhuisinga** [awcodes/alpine-floating-ui#3]
@awcodes - let me just start by saying that this library is excellent! It works just as expected and is very much appreciated.

I'm working on an implementation and am trying to match the size of the dropdown to the reference width using the size middleware (https://floating-ui.com/docs/size). It appears, however, that this library doesn't support the size middleware at all yet. Are there plans on your end for implementing it? If you have no plans to do so I may be able to take a shot at it in the next few weeks.

**Comment by awcodes** [comment]
I didn't see the point of it, but I'll see what I can do. Thanks.

**Comment by aaronhuisinga** [comment]
Thanks @awcodes! My case is [Matching Reference Width](https://floating-ui.com/docs/size#match-reference-width), which would be difficult to do outside of the plugin.

**Comment by awcodes** [comment]
Resolved by #4

**Comment by awcodes** [comment]
This has been released in v3.5.0
