### ISSUE TITLE
Unexpected token '?' on iOS Safari

### ISSUE THREAD

**Issue by abdulmejidshemsu** [awcodes/alpine-floating-ui#5]
We have the following JavaScript error on Safari browser:
SyntaxError: Unexpected token '?'
OS: iOS, 
version: <= v13.3, basically any version that is below v13.4

**for example take the below device as an example** 
![image](https://github.com/awcodes/alpine-floating-ui/assets/53785447/969d4e4d-b505-46e6-8cea-d9876553fcd0)

**Comment by awcodes** [comment]
This plugin uses floating ui and alpine under the hood. Check those two to see if they have support for that browser. There is nothing browser specific in this integration.
