### ISSUE TITLE
Difference to Alpine's Anchor plugin

### ISSUE THREAD

**Issue by buddhaCode** [awcodes/alpine-floating-ui#7]
Hi folks,
what is the difference to the Alpine first-party anchor plugin? They say it's based on Floating UI, too? But this plugin seems to have much more features?!

Best, Arne

**Comment by awcodes** [comment]
Yea, it has more features. This plugin was built before the 'anchor' plugin was built.

We use it in Filament PHP.

**Comment by buddhaCode** [comment]
Thank you for clarification.
